### ISSUE TITLE
python clausie_api.py (  File "/Library/Python/2.7/site-packages/nltk/tokenize/punkt.py", line 1289, in _slices_from_text     for match in self._lang_vars.period_context_re().finditer(text): TypeError: expected string or buffer)

### ISSUE THREAD

**Issue by Bobyuan1015** [drwiner/ClausIEpy#1]
BobdeMacBook-Pro:ClausIEpy-master bob$ python clausie_api.py 
Traceback (most recent call last):
  File "clausie_api.py", line 141, in <module>
    sentences = clausie(text_list=sent_list)
  File "/Volumes/Untitled/PhD/Interview/ClauseIE/Python/ClausIEpy-master/clockdeco.py", line 9, in clocked
    result = func(*args,**kwargs)
  File "clausie_api.py", line 80, in clausie
    text_list = prepare_raw_text(text_list)
  File "clausie_api.py", line 118, in prepare_raw_text
    sents = _sent_detector.tokenize(raw_text)
  File "/Library/Python/2.7/site-packages/nltk/tokenize/punkt.py", line 1237, in tokenize
    return list(self.sentences_from_text(text, realign_boundaries))
  File "/Library/Python/2.7/site-packages/nltk/tokenize/punkt.py", line 1285, in sentences_from_text
    return [text[s:e] for s, e in self.span_tokenize(text, realign_boundaries)]
  File "/Library/Python/2.7/site-packages/nltk/tokenize/punkt.py", line 1276, in span_tokenize
    return [(sl.start, sl.stop) for sl in slices]
  File "/Library/Python/2.7/site-packages/nltk/tokenize/punkt.py", line 1316, in _realign_boundaries
    for sl1, sl2 in _pair_iter(slices):
  File "/Library/Python/2.7/site-packages/nltk/tokenize/punkt.py", line 312, in _pair_iter
    prev = next(it)
  File "/Library/Python/2.7/site-packages/nltk/tokenize/punkt.py", line 1289, in _slices_from_text
    for match in self._lang_vars.period_context_re().finditer(text):
TypeError: expected string or buffer
BobdeMacBook-Pro:ClausIEpy-master bob$ Loading parser from serialized file edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz ... done [2.6 sec].

**Comment by drwiner** [comment]
This is tested with Python 3.x, NLTK 3.2.x. Looks like you're using Python 2.7 and you're having an issue with "punkt.py" in nltk.tokenize (https://www.nltk.org/_modules/nltk/tokenize/punkt.html).

**Comment by Bobyuan1015** [comment]
Hi

I changed python3 but the err is still


BobdeMacBook-Pro:ClausIEpy-master bob$ python3 clausie_api.py 
[<nltk.tokenize.punkt.PunktSentenceTokenizer object at 0x111b7b4e0>]
----------------------------------------
[b'The body floats to the surface of the water.\n', b'He shoots first, asks questions later.\n']
----------------------------------------
Traceback (most recent call last):
  File "clausie_api.py", line 145, in <module>
    sentences = clausie(text_list=sent_list)
  File "/Volumes/Untitled/PhD/Interview/ClauseIE/Python/ClausIEpy-master/clockdeco.py", line 9, in clocked
    result = func(*args,**kwargs)
  File "clausie_api.py", line 80, in clausie
    text_list = prepare_raw_text(text_list)
  File "clausie_api.py", line 122, in prepare_raw_text
    sents = _sent_detector.tokenize(raw_text)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nltk/tokenize/punkt.py", line 1237, in tokenize
    return list(self.sentences_from_text(text, realign_boundaries))
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nltk/tokenize/punkt.py", line 1285, in sentences_from_text
    return [text[s:e] for s, e in self.span_tokenize(text, realign_boundaries)]
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nltk/tokenize/punkt.py", line 1276, in span_tokenize
    return [(sl.start, sl.stop) for sl in slices]
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nltk/tokenize/punkt.py", line 1276, in <listcomp>
    return [(sl.start, sl.stop) for sl in slices]
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nltk/tokenize/punkt.py", line 1316, in _realign_boundaries
    for sl1, sl2 in _pair_iter(slices):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nltk/tokenize/punkt.py", line 312, in _pair_iter
    prev = next(it)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/nltk/tokenize/punkt.py", line 1289, in _slices_from_text
    for match in self._lang_vars.period_context_re().finditer(text):
TypeError: expected string or bytes-like object
BobdeMacBook-Pro:ClausIEpy-master bob$ Loading parser from serialized file edu/stanford/nlp/models/lexparser/englishPCFG.ser.gz ... done [2.5 sec].

**Comment by drwiner** [comment]
Not sure what has changed since this was written: the answer is to wrap a "str(raw_text)" on line 118.  Going to push update. Thanks for raising the issue! - Let me know if this still isn't working for you.

**Comment by Bobyuan1015** [comment]
Thanks 

I fixed it by 'raw_text_sents = ' '.join(raw_text)' in 'def prepare_raw_text(raw_text)'

def prepare_raw_text(raw_text):
	_sent_detector = nltk.data.load('tokenizers/punkt/english.pickle')
	print ([_sent_detector])
	print ('--'*20)
	print (raw_text)
	print ('--'*20)

	raw_text_sents = ' '.join(raw_text)

**Comment by Bobyuan1015** [comment]
Yes , author, you are so fast to fix the problem.
thanks a lot 


str() == join()
